'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const {
  detectAiTool,
  detectFramework,
  detectContentTags,
  detectSuspiciousHostname,
} = require('../lib/fingerprint.js');

test('detectAiTool identifies v0 from HTML comment', () => {
  assert.equal(detectAiTool('<!-- Generated by v0 by Vercel --><html>'), 'v0');
});

test('detectAiTool identifies Lovable from HTML comment', () => {
  assert.equal(detectAiTool('<!-- Built with Lovable --><html>'), 'Lovable');
});

test('detectAiTool returns null for unknown tools', () => {
  assert.equal(detectAiTool('<html><body>hand written</body></html>'), null);
});

test('detectFramework identifies Next.js from header', () => {
  assert.equal(detectFramework('', { 'x-powered-by': 'Next.js' }), 'Next.js');
});

test('detectFramework identifies SvelteKit from HTML', () => {
  assert.equal(detectFramework('window.__sveltekit_data = {};', {}), 'SvelteKit');
});

test('detectFramework returns Static for no signals', () => {
  assert.equal(detectFramework('<html></html>', {}), 'Static');
});

// ── detectContentTags ────────────────────────────────────────────────────

test('detectContentTags tags crypto from hostname alone', () => {
  const tags = detectContentTags('', { title: '', description: '' }, 'ledger-wallet.pages.dev');
  assert.ok(tags?.includes('crypto'), 'should include crypto');
});

test('detectContentTags tags from title when dom is empty', () => {
  const tags = detectContentTags('', { title: 'AI Chat Assistant', description: '' });
  assert.ok(tags?.includes('ai-app'));
});

test('detectContentTags returns null when nothing matches', () => {
  assert.equal(detectContentTags('', { title: '', description: '' }, ''), null);
});

// ── detectSuspiciousHostname ─────────────────────────────────────────────

test('detectSuspiciousHostname flags phishing-shaped names', () => {
  assert.deepEqual(detectSuspiciousHostname('fed-kucoin-login.pages.dev'), ['login']);
  assert.ok(detectSuspiciousHostname('uphold-wallet-us.pages.dev')?.includes('wallet'));
  assert.ok(detectSuspiciousHostname('secure-bank-portal.workers.dev')?.includes('secure'));
});

test('detectSuspiciousHostname returns null for clean hostnames', () => {
  assert.equal(detectSuspiciousHostname('my-portfolio.vercel.app'), null);
  assert.equal(detectSuspiciousHostname('blog-site.pages.dev'), null);
});

test('detectSuspiciousHostname handles empty input', () => {
  assert.equal(detectSuspiciousHostname(''), null);
  assert.equal(detectSuspiciousHostname(null), null);
});
